### ISSUE TITLE
Criar README.md

### ISSUE THREAD

**Issue by amandabrbz** [erikacarvalho/webdev.versionamento#1]
Hey! Our first issue!

**Comment by erikacarvalho** [comment]
adicionei um `README.md` com algumas informações iniciais e deixei um esqueleto para podermos adicionar mais infos mais tarde :nerd_face: 

:link: o commit adicionando o arquivo foi esse aqui: [a7f295c](https://github.com/erikacarvalho/webdev.versionamento/commit/a7f295c0dbce28ed59b92bbdf2e943774aff76ec)
