### ISSUE TITLE
Criar apresentação

### ISSUE THREAD

**Issue by amandabrbz** [erikacarvalho/webdev.versionamento#16]
Criar uma apresentação para a aula de 08/08, falando um pouquinho do nosso projeto. 

Colocar, pelo menos:

- Issues
- Principais comandos que utilizamos
- Diferenciais
- Procedimentos
- etc

**Comment by erikacarvalho** [comment]
a apresentação está pronta!

ela pode ser encontrada [nesse link aqui](https://docs.google.com/presentation/d/16844r-Pp0RhPhDCw0iiYtTFUV0oRKVe8s5b44NI2LlY/edit#slide=id.gcb9a0b074_1_0).

![image](https://user-images.githubusercontent.com/20035639/89700916-d3869600-d908-11ea-9d76-0ee823ddaeb1.png)
