### ISSUE TITLE
Criar componente de cards

### ISSUE THREAD

**Issue by amandabrbz** [erikacarvalho/webdev.versionamento#7]
De acordo com o protótipo, criar componentes de cards.

**Comment by vmaziero** [comment]
Criar componentes de cards contendo a imagem do poster do filme, título, categoria, sinopse, elenco principal e um botão que redireciona para a avaliação do filme no site IMDb.

**Comment by amandabrbz** [comment]
oi @vmaziero, pensando na sua descrição e com o layout que hoje temos disponível, acredito que a página fique muito cheia de informações, submeti um PR que segue o como o protótipo e estava pensando em depois a gente criar mais uma feature que quando clicamos no card do filme ele abra um modal contendo já a página do filme no IMDb. O que acha?

@erikacarvalho  lhe convoco para essa discussão hahaha

**Comment by erikacarvalho** [comment]
eu gostei bastante da ideia da @amandabrbz de colocar o modal com a página do imdb daquele título, assim fica mais clean :D
